# Generated by Django 3.2.1 on 2023-06-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20230612_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
