# Generated by Django 3.2.6 on 2023-06-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20230613_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
